name = "urnitol"
uuid = "e5167ba8-ab0e-4058-9b44-c39cc324ff57"
keywords = ["urn", "ball", "simulator"]
license = "MIT"
desc = "Urn and ball simulator"
version = "0.0.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[targets]
test = ["Test"]
